apiVersion: apps/v1
kind: Deployment
metadata:
  name: listpods-deployment
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: myapp
  template:
    metadata:
      name: listpodsapi
      labels:
        app: myapp
    spec:
      containers:
        - name: listpodscontainer
          image: abhinandan13/listpods:latest
          ports:
            - containerPort: 9090

