apiVersion: v1
kind: Service
metadata:
  name: listpods-service
spec:
  type: NodePort
  ports:
    - targetPort: 9090
      port: 9090
      nodePort: 32000
      protocol: TCP
      name: grpc-port
  selector:
    app: myapp
